### ISSUE TITLE
Licença

### ISSUE THREAD

**Issue by chicocvenancio** [lgelape/texto_mariellefranco#1]
Gostaria de usar os dados e parte do código para montar um mapa interativo como fiz em http://chicocvenancio.github.io/bus_slz.

Nesse momento não há licença no repositório, podes verificar uma licença aberta e compartilhá-lo?

Parabéns pelo trabalho.

**Comment by lgelape** [comment]
Acredito que agora esteja resolvido. Desculpe pela demora. Obrigado!
